/**
 * DCHA RFTA Packet PDF Generator
 *
 * Generates a filled-out version of the DCHA Request for Tenancy Approval
 * packet using the data collected in the voucher wizard. The PDF mirrors
 * the official DCHA RFTA packet structure (30-page packet condensed to
 * the fillable forms).
 *
 * Pages generated:
 *  1. RFTA Cover Sheet (Page 2 of official packet)
 *  2. HUD-52517 Request for Tenancy Approval — Page 1
 *  3. HUD-52517 Request for Tenancy Approval — Page 2 (Certifications)
 *  4. Features and Amenities Form
 *  5. Property Owner/Agent Information Form
 *  6. Direct Deposit Authorization Form
 *  7. HQS Move-In Inspection Checklist
 */

import { jsPDF } from "jspdf";

// Re-use the types from the wizard page
type FormDataInput = {
  jurisdiction: string;
  phaName: string;
  unitAddress: string;
  unitNumber: string;
  unitCity: string;
  unitState: string;
  unitZip: string;
  requestedLeaseStart: string;
  numberOfBedrooms: string;
  yearConstructed: string;
  proposedRent: string;
  securityDeposit: string;
  dateAvailableForInspection: string;
  structureType: string;
  isSubsidized: boolean;
  subsidyType: string;
  utilities: Record<string, "owner" | "tenant">;
  applianceRefrigerator: "owner" | "tenant";
  applianceRange: "owner" | "tenant";
  heatingFuelType: string;
  cookingFuelType: string;
  waterHeatingFuelType: string;
  comparableUnits: { address: string; dateRented: string; amount: string }[];
  noFamilyRelationship: boolean;
  leadPaintStatus: string;
  tenantName: string;
  tenantCurrentAddress: string;
  tenantPhone: string;
  tenantEmail: string;
  voucherNumber: string;
  ownerName: string;
  ownerAddress: string;
  ownerCity: string;
  ownerState: string;
  ownerZip: string;
  ownerPhone: string;
  ownerEmail: string;
  ownerType: string;
  ownerAgentNumber: string;
  isNewOwner: boolean;
  hasScreenedTenant: boolean;
  numberOfBathrooms: string;
  squareFootage: string;
  isRentStabilized: boolean;
  bankName: string;
  accountType: string;
  hapPayeeName: string;
  hapPayeeAddress: string;
  ownerCertifications: Record<string, boolean>;
  hqsChecklist: Record<string, boolean>;
};

const NAVY = "#1e3a5f";
const GRAY = "#64748b";
const LIGHT_GRAY = "#e2e8f0";

const STRUCTURE_LABELS: Record<string, string> = {
  single_family: "Single Family Detached",
  semi_detached: "Semi-Detached (duplex)",
  rowhouse: "Rowhouse/Townhouse",
  low_rise: "Low-rise apartment (4 stories or fewer)",
  high_rise: "High-rise apartment (5+ stories)",
  manufactured: "Manufactured Home",
};

const FUEL_LABELS: Record<string, string> = {
  natural_gas: "Natural Gas",
  bottled_gas: "Bottled Gas",
  electric: "Electric",
  oil: "Oil",
  heat_pump: "Heat Pump",
  other: "Other",
};

function fullAddress(form: FormDataInput) {
  const parts = [form.unitAddress];
  if (form.unitNumber) parts[0] += ` #${form.unitNumber}`;
  parts.push(`${form.unitCity}, ${form.unitState} ${form.unitZip}`);
  return parts.join(", ");
}

function ownerFullAddress(form: FormDataInput) {
  return `${form.ownerAddress}, ${form.ownerCity}, ${form.ownerState} ${form.ownerZip}`;
}

function checkbox(doc: jsPDF, x: number, y: number, checked: boolean) {
  doc.setDrawColor(100, 100, 100);
  doc.setLineWidth(0.3);
  doc.rect(x, y, 3.5, 3.5);
  if (checked) {
    doc.setFont("Helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(0, 100, 0);
    doc.text("X", x + 0.7, y + 3);
    doc.setTextColor(0);
  }
}

function sectionHeader(doc: jsPDF, y: number, text: string): number {
  doc.setFillColor(30, 58, 95); // Navy
  doc.rect(15, y, 180, 7, "F");
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(255);
  doc.text(text, 18, y + 5);
  doc.setTextColor(0);
  return y + 10;
}

function fieldRow(doc: jsPDF, y: number, label: string, value: string, x1 = 15, x2 = 70): number {
  doc.setFont("Helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(100, 100, 100);
  doc.text(label, x1, y);
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(0);
  doc.text(value || "_______________", x2, y);
  doc.setDrawColor(200, 200, 200);
  doc.line(x2, y + 1, 195, y + 1);
  return y + 7;
}

function pageFooter(doc: jsPDF, pageNum: number, totalPages: number) {
  const h = doc.internal.pageSize.height;
  doc.setDrawColor(200, 200, 200);
  doc.line(15, h - 12, 195, h - 12);
  doc.setFont("Helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(150);
  doc.text(`Generated by RentWise AI Voucher Assistant  |  For reference only — submit official forms to ${doc.getNumberOfPages() > 0 ? "DCHA/HAPGC" : "PHA"}`, 15, h - 8);
  doc.text(`Page ${pageNum} of ${totalPages}`, 180, h - 8);
}

export function generateRFTAPdf(form: FormDataInput): jsPDF {
  const doc = new jsPDF({ unit: "mm", format: "letter" });
  const isDC = form.jurisdiction === "dc";
  const agencyName = isDC ? "DCHA" : "HAPGC";
  const totalPages = isDC ? 7 : 5;
  let y = 0;

  // ─── PAGE 1: RFTA COVER SHEET ───────────────────────────
  y = 20;
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(30, 58, 95);
  doc.text("DISTRICT OF COLUMBIA HOUSING AUTHORITY", 105, y, { align: "center" });
  y += 5;
  doc.setFont("Helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(100);
  doc.text("300 7th Street SW | 10th Floor, Washington DC 20024", 105, y, { align: "center" });
  y += 8;
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(0);
  doc.text("REQUEST FOR TENANCY APPROVAL PACKET", 105, y, { align: "center" });
  y += 10;

  // Tenant info box
  y = sectionHeader(doc, y, "TENANT INFORMATION");
  y = fieldRow(doc, y, "Name:", form.tenantName);
  y = fieldRow(doc, y, "Current Address:", form.tenantCurrentAddress);
  y = fieldRow(doc, y, "Phone:", form.tenantPhone);
  y = fieldRow(doc, y, "Email:", form.tenantEmail);
  y = fieldRow(doc, y, "Voucher #:", form.voucherNumber);
  y += 3;

  // Owner info box
  y = sectionHeader(doc, y, "PROPERTY OWNER INFORMATION");
  y = fieldRow(doc, y, "Name:", form.ownerName);
  y = fieldRow(doc, y, "Address:", ownerFullAddress(form));
  y = fieldRow(doc, y, "Phone:", form.ownerPhone);
  y = fieldRow(doc, y, "Email:", form.ownerEmail);
  y += 3;

  // Proposed unit box
  y = sectionHeader(doc, y, "PROPOSED UNIT INFORMATION");
  y = fieldRow(doc, y, "Address:", fullAddress(form));
  y = fieldRow(doc, y, "Proposed Rent:", form.proposedRent ? `$${form.proposedRent}/mo` : "");
  y = fieldRow(doc, y, "Security Deposit:", form.securityDeposit ? `$${form.securityDeposit}` : "");
  y += 3;

  // Owner status
  y += 3;
  doc.setFont("Helvetica", "normal");
  doc.setFontSize(8);
  doc.text("I am a:", 15, y);
  checkbox(doc, 35, y - 3, form.isNewOwner);
  doc.text("New Owner", 40, y);
  checkbox(doc, 65, y - 3, !form.isNewOwner);
  doc.text("Existing Owner/Agent", 70, y);
  if (!form.isNewOwner && form.ownerAgentNumber) {
    doc.text(`#: ${form.ownerAgentNumber}`, 110, y);
  }
  y += 5;

  doc.text("I have screened my potential tenant:", 15, y);
  checkbox(doc, 75, y - 3, form.hasScreenedTenant);
  doc.text("Yes", 80, y);
  checkbox(doc, 95, y - 3, !form.hasScreenedTenant);
  doc.text("No", 100, y);
  y += 8;

  // Required documentation checklist
  y = sectionHeader(doc, y, "REQUIRED DOCUMENTATION CHECKLIST");
  const docs = isDC
    ? [
        "HUD-52517 Request for Tenancy Approval",
        "DCHA Property Owner/Agent Information Form",
        "DCHA Direct Deposit Authorization Form + W-9 + voided check",
        "DCHA Features and Amenities Form",
        "Copy of deed / LLC documentation / Articles of Incorporation",
        "Photo identification matching signatures",
        "Lead inspection report (if built before 1978)",
        "DCHA HQS Move-In Inspection Checklist (signed)",
        "DC Lead Disclosure Form (pre-1978 properties)",
        "DC Tenant Bill of Rights (signed by tenant)",
      ]
    : [
        "HUD-52517 Request for Tenancy Approval",
        "HAPGC New Landlord Packet",
        "Direct Deposit Authorization + voided check",
        "W-9 (Tax ID verification)",
        "Copy of property deed",
        "Lead inspection report (if built before 1978)",
      ];

  docs.forEach((d) => {
    checkbox(doc, 15, y - 3, false);
    doc.setFont("Helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(0);
    doc.text(d, 21, y);
    y += 5;
  });

  pageFooter(doc, 1, totalPages);

  // ─── PAGE 2: HUD-52517 PAGE 1 ──────────────────────────
  doc.addPage();
  y = 15;
  doc.setFont("Helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(100);
  doc.text("U.S. Department of Housing and Urban Development", 15, y);
  doc.text("OMB Approval No. 2577-0169", 160, y);
  y += 5;
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(12);
  doc.setTextColor(0);
  doc.text("Request for Tenancy Approval", 105, y, { align: "center" });
  y += 4;
  doc.setFontSize(8);
  doc.setTextColor(100);
  doc.text("Housing Choice Voucher Program  |  HUD Form 52517", 105, y, { align: "center" });
  y += 8;

  // Fields 1-8
  y = sectionHeader(doc, y, "SECTION 1-8: UNIT INFORMATION");
  y = fieldRow(doc, y, "1. Name of PHA:", form.phaName);
  y = fieldRow(doc, y, "2. Address of Unit:", fullAddress(form));
  y = fieldRow(doc, y, "3. Requested Lease Start:", form.requestedLeaseStart);
  y = fieldRow(doc, y, "4. Number of Bedrooms:", form.numberOfBedrooms);
  y = fieldRow(doc, y, "5. Year Constructed:", form.yearConstructed);
  y = fieldRow(doc, y, "6. Proposed Rent:", form.proposedRent ? `$${form.proposedRent}` : "");
  y = fieldRow(doc, y, "7. Security Deposit:", form.securityDeposit ? `$${form.securityDeposit}` : "");
  y = fieldRow(doc, y, "8. Date Available:", form.dateAvailableForInspection);
  y += 3;

  // Field 9: Structure type
  y = sectionHeader(doc, y, "SECTION 9: STRUCTURE TYPE");
  const structureLabel = STRUCTURE_LABELS[form.structureType] || "";
  Object.entries(STRUCTURE_LABELS).forEach(([key, label]) => {
    checkbox(doc, 15, y - 3, form.structureType === key);
    doc.setFont("Helvetica", "normal");
    doc.setFontSize(8);
    doc.text(label, 21, y);
    y += 5;
  });
  y += 2;

  // Field 10: Subsidy
  y = sectionHeader(doc, y, "SECTION 10: SUBSIDY");
  checkbox(doc, 15, y - 3, !form.isSubsidized);
  doc.setFont("Helvetica", "normal");
  doc.setFontSize(8);
  doc.text("Not subsidized", 21, y);
  checkbox(doc, 65, y - 3, form.isSubsidized);
  doc.text(form.isSubsidized ? `Subsidized: ${form.subsidyType}` : "Subsidized (specify type)", 71, y);
  y += 7;

  // Field 11: Utilities
  y = sectionHeader(doc, y, "SECTION 11: UTILITIES AND APPLIANCES");
  doc.setFontSize(7);
  doc.setTextColor(100);
  doc.text("O = Owner pays  |  T = Tenant pays", 15, y);
  y += 4;

  // Table header
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(0);
  doc.text("Item", 15, y);
  doc.text("Fuel Type", 70, y);
  doc.text("Paid By", 130, y);
  doc.setDrawColor(100);
  doc.line(15, y + 1, 195, y + 1);
  y += 5;

  const utilRows: [string, string, string][] = [
    ["Heating", FUEL_LABELS[form.heatingFuelType] || "", form.utilities.heating?.toUpperCase() || "O"],
    ["Cooking", FUEL_LABELS[form.cookingFuelType] || "", form.utilities.cooking?.toUpperCase() || "O"],
    ["Water Heating", FUEL_LABELS[form.waterHeatingFuelType] || "", form.utilities.waterHeating?.toUpperCase() || "O"],
    ["Other Electric", "", form.utilities.otherElectric?.toUpperCase() || "O"],
    ["Water", "", form.utilities.water?.toUpperCase() || "O"],
    ["Sewer", "", form.utilities.sewer?.toUpperCase() || "O"],
    ["Trash Collection", "", form.utilities.trash?.toUpperCase() || "O"],
    ["Air Conditioning", "", form.utilities.airConditioning?.toUpperCase() || "O"],
  ];

  doc.setFont("Helvetica", "normal");
  utilRows.forEach(([item, fuel, paidBy]) => {
    doc.text(item, 15, y);
    doc.text(fuel, 70, y);
    doc.setFont("Helvetica", "bold");
    doc.text(paidBy, 135, y);
    doc.setFont("Helvetica", "normal");
    y += 5;
  });
  y += 2;

  // Appliances
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(8);
  doc.text("Appliances Provided By:", 15, y);
  y += 5;
  doc.setFont("Helvetica", "normal");
  doc.text(`Refrigerator: ${form.applianceRefrigerator === "owner" ? "Owner" : "Tenant"}`, 15, y);
  doc.text(`Range/Microwave: ${form.applianceRange === "owner" ? "Owner" : "Tenant"}`, 90, y);

  pageFooter(doc, 2, totalPages);

  // ─── PAGE 3: HUD-52517 PAGE 2 (Certifications) ─────────
  doc.addPage();
  y = 15;
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(10);
  doc.text("HUD-52517 — Owner's Certifications (Sections 12-15)", 105, y, { align: "center" });
  y += 8;

  // 12a: Comparable units
  y = sectionHeader(doc, y, "12a. COMPARABLE UNASSISTED UNITS");
  doc.setFont("Helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(100);
  doc.text("For projects with more than 4 units: list most recently leased comparable unassisted units.", 15, y);
  y += 5;
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(8);
  doc.setTextColor(0);
  doc.text("#", 15, y); doc.text("Address and Unit Number", 22, y); doc.text("Date Rented", 110, y); doc.text("Rental Amount", 150, y);
  doc.line(15, y + 1, 195, y + 1);
  y += 5;
  doc.setFont("Helvetica", "normal");
  form.comparableUnits.forEach((cu, i) => {
    doc.text(`${i + 1}.`, 15, y);
    doc.text(cu.address || "___________________", 22, y);
    doc.text(cu.dateRented || "___________", 110, y);
    doc.text(cu.amount ? `$${cu.amount}` : "___________", 150, y);
    y += 5;
  });
  y += 5;

  // 12b: Family relationship
  y = sectionHeader(doc, y, "12b. FAMILY RELATIONSHIP CERTIFICATION");
  checkbox(doc, 15, y - 3, form.noFamilyRelationship);
  doc.setFont("Helvetica", "normal");
  doc.setFontSize(8);
  doc.text("The owner is NOT the parent, child, grandparent, grandchild, sister, or brother", 21, y);
  y += 4;
  doc.text("of any member of the family.", 21, y);
  y += 8;

  // 12c: Lead paint
  y = sectionHeader(doc, y, "12c. LEAD-BASED PAINT STATUS");
  const leadOpts = [
    { key: "post1978", label: "Lead-based paint requirements do not apply (built on or after Jan 1, 1978)" },
    { key: "certified_free", label: "Unit found to be lead-based paint free by a certified inspector" },
    { key: "disclosure_attached", label: "A completed lead-based paint disclosure statement is attached" },
  ];
  leadOpts.forEach((opt) => {
    checkbox(doc, 15, y - 3, form.leadPaintStatus === opt.key);
    doc.setFont("Helvetica", "normal");
    doc.setFontSize(8);
    doc.text(opt.label, 21, y);
    y += 6;
  });
  y += 5;

  // 13-15: Other certifications
  y = sectionHeader(doc, y, "SECTIONS 13-15: OWNER CERTIFICATIONS");
  const certTexts = [
    ["noConflict", "Owner is not related to any member of the tenant family (HUD Section 12b)"],
    ["unitMeetsHQS", "Unit meets Housing Quality Standards or will be brought into compliance"],
    ["willMaintain", "Owner agrees to maintain the unit per HQS throughout tenancy"],
    ["noSidePayments", "Owner will not collect side payments beyond approved tenant rent portion"],
    ["accurateInfo", "All information is true and correct (18 U.S.C. 287, 1001, 1010, 1012)"],
  ];
  certTexts.forEach(([key, text]) => {
    checkbox(doc, 15, y - 3, form.ownerCertifications[key] || false);
    doc.setFont("Helvetica", "normal");
    doc.setFontSize(8);
    doc.text(text, 21, y);
    y += 6;
  });
  y += 10;

  // Signature lines
  doc.setFont("Helvetica", "normal");
  doc.setFontSize(8);
  doc.text("Owner/Agent Signature: _______________________________", 15, y);
  doc.text("Date: ________________", 140, y);
  y += 10;
  doc.text("Print Name: _________________________________________", 15, y);

  pageFooter(doc, 3, totalPages);

  // ─── PAGE 4: FEATURES AND AMENITIES (DC only) ──────────
  if (isDC) {
    doc.addPage();
    y = 15;
    doc.setFont("Helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(30, 58, 95);
    doc.text("DISTRICT OF COLUMBIA HOUSING AUTHORITY", 105, y, { align: "center" });
    y += 5;
    doc.setFontSize(7);
    doc.setTextColor(100);
    doc.text("300 7th Street SW | 10th Floor, Washington DC 20024", 105, y, { align: "center" });
    y += 8;
    doc.setFont("Helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.text("Features and Amenities Form", 105, y, { align: "center" });
    y += 10;

    y = fieldRow(doc, y, "Prospective Address:", fullAddress(form));
    y = fieldRow(doc, y, "Number of Bathrooms:", form.numberOfBathrooms);
    y = fieldRow(doc, y, "Square Footage:", form.squareFootage);
    y += 3;
    doc.setFont("Helvetica", "normal");
    doc.setFontSize(8);
    doc.text("Is the unit rent stabilized or under rent control?", 15, y);
    checkbox(doc, 100, y - 3, form.isRentStabilized);
    doc.text("Yes", 105, y);
    checkbox(doc, 115, y - 3, !form.isRentStabilized);
    doc.text("No", 120, y);
    y += 8;

    doc.setFontSize(7);
    doc.setTextColor(100);
    doc.text("Note: The inspection team will confirm all items during initial inspection.", 15, y);
    doc.text("This may affect Rent Reasonableness results if items are not true and complete.", 15, y + 4);

    pageFooter(doc, 4, totalPages);
  }

  // ─── PAGE 5: PROPERTY OWNER/AGENT INFO (DC only) ───────
  if (isDC) {
    doc.addPage();
    y = 15;
    doc.setFont("Helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(30, 58, 95);
    doc.text("DISTRICT OF COLUMBIA HOUSING AUTHORITY", 105, y, { align: "center" });
    y += 5;
    doc.setFontSize(7);
    doc.setTextColor(100);
    doc.text("300 7th Street SW | 10th Floor, Washington DC 20024", 105, y, { align: "center" });
    y += 8;
    doc.setFont("Helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.text("PROPERTY OWNER/AGENT INFORMATION FORM", 105, y, { align: "center" });
    y += 10;

    doc.setFont("Helvetica", "normal");
    doc.setFontSize(8);
    doc.text("I certify that I am a:", 15, y);
    checkbox(doc, 55, y - 3, form.isNewOwner);
    doc.text("new owner/agent", 60, y);
    checkbox(doc, 100, y - 3, !form.isNewOwner);
    doc.text("existing owner", 105, y);
    y += 8;

    y = sectionHeader(doc, y, "A. RENTAL PROPERTY INFORMATION");
    y = fieldRow(doc, y, "Property Address:", fullAddress(form));
    y += 3;

    y = sectionHeader(doc, y, "B. OWNER INFORMATION");
    y = fieldRow(doc, y, "Owner Name:", form.ownerName);
    y = fieldRow(doc, y, "Entity Type:", form.ownerType);
    y = fieldRow(doc, y, "Address:", ownerFullAddress(form));
    y = fieldRow(doc, y, "Phone:", form.ownerPhone);
    y = fieldRow(doc, y, "Email:", form.ownerEmail);
    y += 2;
    doc.setFont("Helvetica", "italic");
    doc.setFontSize(7);
    doc.setTextColor(100);
    doc.text("Tax ID / SSN: Enter on official form only (not stored by RentWise)", 15, y);
    y += 8;

    y = sectionHeader(doc, y, "D. PAYEE INFORMATION");
    y = fieldRow(doc, y, "Payee Name:", form.hapPayeeName);
    y = fieldRow(doc, y, "Payee Address:", form.hapPayeeAddress);
    y += 10;

    doc.setFont("Helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(0);
    doc.text("Signature of Owner/Agent: _______________________________", 15, y);
    doc.text("Date: ________________", 140, y);

    pageFooter(doc, 5, totalPages);
  }

  // ─── PAGE 6: DIRECT DEPOSIT (DC only) ──────────────────
  if (isDC) {
    doc.addPage();
    y = 15;
    doc.setFont("Helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(30, 58, 95);
    doc.text("DISTRICT OF COLUMBIA HOUSING AUTHORITY", 105, y, { align: "center" });
    y += 5;
    doc.setFontSize(7);
    doc.setTextColor(100);
    doc.text("300 7th Street SW | 10th Floor, Washington DC 20024", 105, y, { align: "center" });
    y += 8;
    doc.setFont("Helvetica", "bold");
    doc.setFontSize(12);
    doc.setTextColor(0);
    doc.text("DIRECT DEPOSIT AUTHORIZATION AGREEMENT FORM", 105, y, { align: "center" });
    y += 10;

    doc.setFont("Helvetica", "normal");
    doc.setFontSize(8);
    doc.text("Please select the action that best applies:", 15, y);
    y += 5;
    checkbox(doc, 15, y - 3, form.isNewOwner);
    doc.text("I am a new owner/agent and want to set up a new direct deposit account.", 21, y);
    y += 5;
    checkbox(doc, 15, y - 3, !form.isNewOwner);
    doc.text("I am an existing owner/agent who would like to continue using my account on file.", 21, y);
    y += 8;

    y = fieldRow(doc, y, "Name of Financial Institution:", form.bankName);
    y += 2;
    doc.text("Account Type:", 15, y);
    checkbox(doc, 55, y - 3, form.accountType === "checking");
    doc.text("Checking", 60, y);
    checkbox(doc, 85, y - 3, form.accountType === "savings");
    doc.text("Savings", 90, y);
    y += 7;
    y = fieldRow(doc, y, "Payee Name:", form.hapPayeeName);
    y = fieldRow(doc, y, "Address:", form.hapPayeeAddress);
    y += 5;

    doc.setFont("Helvetica", "italic");
    doc.setFontSize(7);
    doc.setTextColor(100);
    doc.text("Routing number, account number, and SSN/Tax ID: Enter on official DCHA form only.", 15, y);
    y += 4;
    doc.text("Attach a voided check, letter from your financial institution, or savings account deposit slip.", 15, y);
    y += 10;

    doc.setFont("Helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(0);
    doc.text("Signature of Owner or Authorized Person: _______________________________", 15, y);
    doc.text("Date: ____________", 155, y);

    pageFooter(doc, 6, totalPages);
  }

  // ─── LAST PAGE: HQS CHECKLIST ──────────────────────────
  doc.addPage();
  y = 15;
  const lastPageNum = isDC ? 7 : 4;
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(30, 58, 95);
  doc.text(isDC ? "DISTRICT OF COLUMBIA HOUSING AUTHORITY" : "HQS INSPECTION PREP", 105, y, { align: "center" });
  y += isDC ? 5 : 3;
  if (isDC) {
    doc.setFontSize(7);
    doc.setTextColor(100);
    doc.text("300 7th Street SW | 10th Floor, Washington DC 20024", 105, y, { align: "center" });
    y += 5;
  }
  doc.setFont("Helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(0);
  doc.text("HCVP HQS MOVE-IN INSPECTION CHECKLIST", 105, y, { align: "center" });
  y += 8;

  y = fieldRow(doc, y, "Address of Proposed Unit:", fullAddress(form));
  y = fieldRow(doc, y, "Proposed Tenant Name:", form.tenantName);
  y = fieldRow(doc, y, "Owner of Record:", form.ownerName);
  y += 3;

  // Import HQS_CHECKLIST dynamically would be circular — instead, just show checked items count
  const checkedCount = Object.values(form.hqsChecklist).filter(Boolean).length;
  const totalItems = Object.keys(form.hqsChecklist).length || 44;

  doc.setFont("Helvetica", "bold");
  doc.setFontSize(9);
  doc.text(`Items verified: ${checkedCount} of ${totalItems}`, 15, y);
  y += 7;

  // Show key categories with checked status
  const categories = [
    "General / Safety", "Kitchen / Bathroom", "Bedrooms", "Exterior / Entry",
    "Mechanical Systems", "Health & Safety",
  ];
  categories.forEach((cat) => {
    checkbox(doc, 15, y - 3, checkedCount > 0);
    doc.setFont("Helvetica", "normal");
    doc.setFontSize(8);
    doc.text(cat, 21, y);
    y += 5;
  });
  y += 5;

  doc.setFont("Helvetica", "normal");
  doc.setFontSize(7);
  doc.setTextColor(100);
  doc.text("I, as the owner/agent/landlord of the property hereby acknowledge that all applicable", 15, y);
  y += 4;
  doc.text("conditions above have been checked and comply with Housing Quality Standards (HQS).", 15, y);
  y += 10;

  doc.setFont("Helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(0);
  doc.text("Owner/Landlord Signature: _______________________________", 15, y);
  doc.text("Date: ________________", 140, y);

  pageFooter(doc, lastPageNum, totalPages);

  return doc;
}
